In [2]:
from PolarisOpt import sampler, manager
import json
%load_ext autoreload
%autoreload 2

In [36]:
s = sampler.MorrisSampler('/home/vsokolov/projects/timing-austin/test/var_config.json','/home/vsokolov/projects/timing-austin/test/test-study',1,2)
print(len(s.samples))

Loading samples from /home/vsokolov/projects/timing-austin/test/test-study
7


In [3]:
for i in range(s.p):
    print(s.varnames[i],s.varfiles[i],s.samples[0].input[i])


a file1.json -1.0
b file1.json 0.0
c file2.json -1.0
d file2.json 0.0
S_AMPEAK_TT CampoTimingChoiceModel.json -1.0
S_AMOFFPEAK_TTV CampoTimingChoiceModel.json 0.0


In [5]:
for x in s.samples:
    print(x.input)

[-1.  0. -1.  0. -1.  0.]
[-1.  0.  0.  0. -1.  0.]
[-1.  0.  0.  0.  0.  0.]
[-1. -1.  0.  0.  0.  0.]
[-1. -1.  0. -1.  0.  0.]
[ 0. -1.  0. -1.  0.  0.]
[ 0. -1.  0. -1.  0. -1.]


In [34]:
for item in s.samples: item.status = 'pending'
len(s.getsamples(max=20))

0

In [18]:
for item in s.samples: item.status = 'pending'
m = manager.Manager('/home/vsokolov/projects/timing-austin/test/settings_test.json',s)
print(m.working_dir)
print(m.num_parallel_runs)
m.run_study()

/home/vsokolov/projects/timing-austin/test/
10
INFO: folder: /home/vsokolov/projects/timing-austin/test/experiments/Sim0 was created but the task was not completed, removing the outputs
INFO: folder: /home/vsokolov/projects/timing-austin/test/experiments/Sim2 was created but the task was not completed, removing the outputs
INFO: folder: /home/vsokolov/projects/timing-austin/test/experiments/Sim6 was created but the task was not completed, removing the outputs
INFO: folder: /home/vsokolov/projects/timing-austin/test/experiments/Sim3 was created but the task was not completed, removing the outputs
INFO: folder: /home/vsokolov/projects/timing-austin/test/experiments/Sim5 was created but the task was not completed, removing the outputs
INFO: folder: /home/vsokolov/projects/timing-austin/test/experiments/Sim1 was created but the task was not completed, removing the outputs
INFO: folder: /home/vsokolov/projects/timing-austin/test/experiments/Sim4 was created but the task was not completed, r

UnboundLocalError: cannot access local variable 'res' where it is not associated with a value

In [9]:
import numpy as np
default = [-0.1,0,0,-0.1,-0.1,-0.1,-0.31,-0.71,-0.32,0,0,0]
manual = [-0.3234, -1.3213,  0.7050, -1.8785,  0.6472,  0.2259, -1.4005, -0.3865,-0.4250, -3.4885, -0.2371, -0.9708]
varnames=['S_AMPEAK_TT','S_AMOFFPEAK_TTV','S_AMOFFPEAK_TT','S_PMOFFPEAK_TT','S_PMPEAK_TT','S_EVENING_TT','S_AMOFFPEAK_OCCUPANCY','S_PMOFFPEAK_OCCUPANCY','S_PMPEAK_OCCUPANCY','D_AMPEAK_OCCUPANCY','D_AMOFFPEAK_OCCUPANCY','D_PMOFFPEAK_OCCUPANCY']
varfiles = ['CampoTimingChoiceModel.json']*12
X = np.array([default,manual])
s = sampler.ManualSampler(X,varnames,varfiles,'quantile-samples')

In [16]:
for x in s.getsamples():
    print(x.__dict__)

{'input': array([-0.1 ,  0.  ,  0.  , -0.1 , -0.1 , -0.1 , -0.31, -0.71, -0.32,
        0.  ,  0.  ,  0.  ]), 'hash': -355961303470610788, 'index': 0, 'status': 'pending', 'output': None, 'folder': None}
{'input': array([-0.3234, -1.3213,  0.705 , -1.8785,  0.6472,  0.2259, -1.4005,
       -0.3865, -0.425 , -3.4885, -0.2371, -0.9708]), 'hash': -6083532848951329444, 'index': 1, 'status': 'pending', 'output': None, 'folder': None}
